name: multitask_rl
exp_name: Atari-Assault

tasks:
  Atari-Assault:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: AssaultNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: param_data/Atari-Assault/data.pt
      k: 200
      num_workers: 4