defaults:
  #- task: Atari-Alien    #used for collect data
  - task: mix           #used for train multitask LDM
  - system: multitask_ae_ddpm

  - _self_

device:
  cuda_visible_devices:  "0"
  #id: [0,1]
  id: [0]
  #cuda: cuda:${device.id}

load_system_checkpoint: "/mnt/kaiwu-group-x3/jiateliu/policy-diffusion/new_outputs/mix20/noae_ddpmepisodecondition_dropout0.1_ps32/20240809-053659-seed42/multitask_episode_ddpm/checkpoints/ddpm-epoch=44999-mean_g_acc=0.1695.ckpt"
#load_system_checkpoint: "/mnt/kaiwu-group-x3/jiateliu/policy-diffusion/new_outputs/mix5/noae_ddpmepisodecondition_ps32/20240724-065355-seed42/multitask_episode_ddpm/checkpoints/ddpm-epoch=49999-mean_g_acc=0.7249.ckpt"
mode: train

seed: 42
process_title: PDN

#output_dir: new_outputs/${task.exp_name}
output_dir: new_outputs/${task.exp_name}/${now:%Y%m%d}-${now:%H%M%S}-seed${seed}

hydra:
  output_subdir: config
  run:
    dir: ${output_dir}
  sweep:
    dir: ${output_dir}
    subdir: ${hydra.job.override_dirname}
